import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Link,
  Preview,
  Text,
  Section,
  Hr,
  Button,
} from 'npm:@react-email/components@0.0.22'
import * as React from 'npm:react@18.3.1'

interface RegistrationFailureEmailProps {
  failures: Array<{
    id: string
    user_id: string
    user_email: string
    error_message: string
    attempted_at: string
  }>
  totalCount: number
  timestamp: string
  adminDashboardUrl: string
}

export const RegistrationFailureEmail = ({
  failures,
  totalCount,
  timestamp,
  adminDashboardUrl
}: RegistrationFailureEmailProps) => {
  return (
    <Html>
      <Head />
      <Preview>FAILURE: User Registration Issues Detected - Sales Whisperer</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={alertHeader}>
            <Text style={alertIcon}>🚨</Text>
            <Heading style={alertTitle}>FAILURE: User Registration Issues Detected</Heading>
            <Text style={alertSubtitle}>Sales Whisperer System Alert</Text>
          </Section>

          <Section style={content}>
            <Section style={summaryBox}>
              <Heading style={summaryTitle}>Alert Summary</Heading>
              <Text style={summaryItem}><strong>Total Affected Users:</strong> {totalCount}</Text>
              <Text style={summaryItem}><strong>Detection Time:</strong> {new Date(timestamp).toLocaleString()}</Text>
              <Text style={summaryItem}><strong>Issue:</strong> Users created in auth.users but failed to sync to public.users table</Text>
            </Section>

            <Heading style={h2}>Affected Users:</Heading>
            
            {failures.map((failure, index) => (
              <Section key={failure.id} style={failureBox}>
                <Text style={failureIndex}>#{index + 1}</Text>
                <Text style={failureDetail}><strong>Email:</strong> {failure.user_email}</Text>
                <Text style={failureDetail}><strong>Time:</strong> {new Date(failure.attempted_at).toLocaleString()}</Text>
                <Text style={failureDetail}><strong>Error:</strong> {failure.error_message}</Text>
                <Text style={failureDetailCode}><strong>User ID:</strong> {failure.user_id}</Text>
              </Section>
            ))}

            <Section style={actionBox}>
              <Heading style={actionTitle}>🔧 Immediate Actions Required:</Heading>
              <Text style={actionItem}>1. Review the failed user registrations above</Text>
              <Text style={actionItem}>2. Run the fix_orphaned_auth_users() function to repair the users</Text>
              <Text style={actionItem}>3. Monitor for additional failures</Text>
              <Text style={actionItem}>4. Investigate root cause if pattern emerges</Text>
            </Section>

            <Section style={ctaSection}>
              <Button pX={32} pY={16} style={button} href={adminDashboardUrl}>
                🔧 Go to Admin Dashboard
              </Button>
            </Section>

            <Section style={technicalBox}>
              <Heading style={technicalTitle}>Technical Details:</Heading>
              <Text style={technicalText}>
                This alert was triggered by the monitor-registration-failures function. 
                The handle_new_user() trigger failed to create public.users records for the affected users.
                Users can still authenticate but may experience issues uploading transcripts due to RLS policies.
              </Text>
            </Section>

            <Hr style={hr} />

            <Section style={footer}>
              <Text style={footerText}>
                This alert was automatically generated by Sales Whisperer monitoring system at {new Date(timestamp).toLocaleString()}
              </Text>
            </Section>
          </Section>
        </Container>
      </Body>
    </Html>
  )
}

export default RegistrationFailureEmail

const main = {
  backgroundColor: '#fef2f2',
  fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
}

const container = {
  margin: '0 auto',
  padding: '40px 20px',
  maxWidth: '800px',
}

const alertHeader = {
  textAlign: 'center' as const,
  marginBottom: '32px',
  padding: '32px',
  backgroundColor: '#fee2e2',
  borderRadius: '12px',
  border: '2px solid #ef4444',
}

const alertIcon = {
  fontSize: '48px',
  margin: '0 0 16px 0',
}

const alertTitle = {
  color: '#dc2626',
  fontSize: '28px',
  fontWeight: '700',
  margin: '0 0 8px 0',
  lineHeight: '1.2',
}

const alertSubtitle = {
  color: '#7f1d1d',
  fontSize: '16px',
  fontWeight: '500',
  margin: '0',
  lineHeight: '1.4',
}

const content = {
  backgroundColor: '#ffffff',
  padding: '40px 32px',
  borderRadius: '12px',
  border: '1px solid #e5e7eb',
}

const summaryBox = {
  backgroundColor: '#f8f9fa',
  padding: '24px',
  borderRadius: '8px',
  marginBottom: '32px',
  border: '1px solid #e5e7eb',
}

const summaryTitle = {
  color: '#374151',
  fontSize: '18px',
  fontWeight: '600',
  margin: '0 0 16px 0',
}

const summaryItem = {
  color: '#374151',
  fontSize: '14px',
  lineHeight: '1.5',
  margin: '0 0 8px 0',
}

const h2 = {
  color: '#374151',
  fontSize: '20px',
  fontWeight: '600',
  margin: '0 0 24px 0',
  lineHeight: '1.3',
}

const failureBox = {
  backgroundColor: '#fff5f5',
  padding: '20px',
  borderRadius: '8px',
  marginBottom: '16px',
  borderLeft: '4px solid #ef4444',
}

const failureIndex = {
  color: '#dc2626',
  fontSize: '12px',
  fontWeight: '700',
  margin: '0 0 8px 0',
  textTransform: 'uppercase' as const,
}

const failureDetail = {
  color: '#374151',
  fontSize: '14px',
  lineHeight: '1.5',
  margin: '0 0 6px 0',
}

const failureDetailCode = {
  color: '#6b7280',
  fontSize: '12px',
  fontFamily: 'monospace',
  lineHeight: '1.5',
  margin: '0',
  wordBreak: 'break-all' as const,
}

const actionBox = {
  backgroundColor: '#f0f9ff',
  padding: '24px',
  borderRadius: '8px',
  margin: '32px 0',
  borderLeft: '4px solid #3b82f6',
}

const actionTitle = {
  color: '#1e40af',
  fontSize: '16px',
  fontWeight: '600',
  margin: '0 0 16px 0',
}

const actionItem = {
  color: '#374151',
  fontSize: '14px',
  lineHeight: '1.6',
  margin: '0 0 8px 0',
}

const ctaSection = {
  textAlign: 'center' as const,
  margin: '32px 0',
}

const button = {
  backgroundColor: '#dc2626',
  borderRadius: '8px',
  color: '#ffffff',
  fontSize: '16px',
  fontWeight: '600',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  border: 'none',
  cursor: 'pointer',
}

const technicalBox = {
  backgroundColor: '#fffbeb',
  padding: '20px',
  borderRadius: '8px',
  borderLeft: '4px solid #f59e0b',
  margin: '32px 0',
}

const technicalTitle = {
  color: '#92400e',
  fontSize: '14px',
  fontWeight: '600',
  margin: '0 0 12px 0',
}

const technicalText = {
  color: '#92400e',
  fontSize: '14px',
  lineHeight: '1.5',
  margin: '0',
}

const hr = {
  border: 'none',
  borderTop: '1px solid #e5e7eb',
  margin: '32px 0',
}

const footer = {
  textAlign: 'center' as const,
}

const footerText = {
  color: '#6b7280',
  fontSize: '12px',
  lineHeight: '1.4',
  margin: '0',
}